### PR TITLE
Proposed resolution for issue #79.

### PR DESCRIPTION
**Pull request by gheber**

### CODE REVIEW

**Comment by hokb** [comment]
Besides looking for the concrete dll names in special folders (which makes quite some assumptions and comes with several drawbacks in terms of maintenance and stability) you could simply try to load the HDF5 dll which depends on MSVCRT in a more failsafe manner. Use try / catch to catch all potential dll loading errors and rethrow any exception to the user. 

The proposed solution will work in many cases, though. But potential pitfalls are: 
* We may forget to maintain the dll names. When hdf5.dll is build in another Visual Studio verison it will reference another msvcrt... 
* Evel character casing issues when comparing with String.Equal()
* We make the assumption to know where the MSVCRT are installed. Dunno if this assumption is valid and will be valid in the future. 

Furthermore, the current implementation seems to prepare for some AnyCPU scenario? Maybe it would be enough to test for 32bit OR 64 bit dependencies only?

**Comment by gheber** [comment]
I see your concern(s). I think the exceptions generated are rather unspecific, i.e., it'll say something like `"hdf5.dll or one of its dependencies couldn't be loaded, yada, yada, yada."` Since `hdf5.dll` also depends on `szip.dll`, `zlib.dll`, etc. it could be any of those. I think this is more targeted at the VC runtime. I'm also thinking about adding the native binaries to the repository. That way I could reference them from the AppVeyor test setup. Any thoughts on that (i.e., including native binaries)?

**Comment by hokb** [comment]
When trying to load hdf5.dll it will not complain about missing dependencies immediately. Dependencies are lazy loaded at the time it is needed for the first time.

**Comment by DSanchen** [comment]
When knowing the name of the dependency, you could also simply try to load that dependency with H5WindowsDLLImporter.LoadLibrary/GetModuleHandle. That would free you from knowing **where** the dependency lies. But the naming issue remains. When using the VS2015 prebuild HDF5 binary, the dependency changes to vcruntime140.dll.
Having all native binaries in the repo would be at least nice, as the consumer of this library (the developer of some app...) could see that there **are** native dependencies. How she redistributes those dependencies is out of our scope, I guess.
So one could ask, if it's our responsibility to check for dependencies of our dependencies ? Redistribute them, yes, but checking if they are "installed" correctly ??? :confused: ?

**Pull request closed without merging**
