### PR TITLE
Support for .Net Standard 2.0 (Windows + Linux)

### PR DESCRIPTION
**Pull request by surban**
These changes allow HDF.PInvoke to be built as a .Net Standard 2.0 library. The resulting library can be used in a .Net Standard/Core 2.0 project and full .Net >= 4.6 (NetFx) projects.

The main work consisted of finding out how .net core handles DllImports. It turns out that it always searches for native libraries in the directory of the library assembly, i.e. where HDF.PInvoke.dll is located. In .net core this is not necessarily the output directory of the consuming project, since dependencies are loaded directly from the NuGet cache without copying them to the project output directory. Thus using HDF.PInvoke.targets as before does not work and the correct method seems to be to include the native libraries as "None" in HDF.PInvoke.csproj. However, HDF.PInvoke.targets is still used when the library is used in a NetFx project and thus this file is kept.

I added the native libraries for Linux by downloading the official builds from the HDF5 website. Since modifying LD_LIBRARY_PATH on Linux has no effect from within a running program, the native libs (libhdf5.so and libhdf5_hl.so) must be in the assembly directory and cannot be placed into bin32 or bin64 respectively. Since official HDF5 builds only support 64-bit Linux, this seems not to be a big deal.

All tests are passing except H5Lget_name_by_idxTest2, which I disabled for now. I don't have an idea why it is not working; perhaps someone can look into it.

I tested the resulting NuGet package using .Net core 2.0 on Linux and Windows and .Net 4.6 with Visual Studio 2017 on Windows.

For building the package on Linux, Mono is (still) required to run FAKE, although only the compilers from .net core are used.

### CODE REVIEW

**Comment by gheber** [comment]
Let's have a conversation to talk about this pull request! I'm not sure I fully understand it. Send [me](mailto:gheber@hdfgroup.org) your contact info and I'll set up a Hangout.

**Comment by linux-fan-dave** [comment]
It would be really great to have this code available. It works for me as well - I tested it under Linux and works great. It only is a bit cumbersome to use since there is no nuget packet is available.

**Comment by Apollo3zehn** [comment]
I think the native dependencies should be structured differently. If I see it correctly they are currently located in the `./native` folder directly. I have no big experience but I am also trying to include a native library in a .nupkg in my own project. Here is what I found out so far reading through many Nuget.Client and corefx issues:

**.csproj:**

Place all native libraries in the .nupkg file with a structure like `runtimes/{rid}/native/` where `{rid}` should be one of [these](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog) (e.g. `win`, `win7-x86` or `linux-x64`). The file path within the package can be specified like so in the .csproj file:

```
<None Include="<path/nativeFile.dll>" Link="runtimes\win-x86\native\nativeFile.dll">
  <Pack>true</Pack>
  <PackagePath>runtimes\win-x86\native</PackagePath>
</None>
```

When referencing a NuGet package with files structured like this, the native dependencies will be resolved by the tooling (I am using VS 2017.6 and the new .csproj format) and a project.assets.json file will be written with all found references to the `obj` folder.

When compiling / publishing the application referencing the package, different things will happen, depending on the configuration:

`<TF> = <TargetFramework>`
`<RID> = <RuntimeIdentifier>`
`%rootFolder% = %localappdata%./nuget/.nuget/packages/hdf.pinvoke/1.10.x`

**Compiling**
- `<TF>net471</TF>` & `<RID>any</RID>`
  - no files will be copied to the application's output folder, **the application does not work**
- `<TF>net471</TF>` & `<RID>win7-x86</RID>`
  - the files contained in folder  `%rootFolder%/runtimes/{win7-x86}/native/` will be copied to the application's output folder, if the folder `win7-x86` are available (flat hierachy). **Otherwise the application does not work**.
- `<TF>netcoreapp2.0</TF>` & `<RID>any</RID>`
  - no files will be copied to the application's output folder, the correct dependencies are resolved during runtime using `deps.json`
- `<TF>netcoreapp2.0</TF>` & `<RID>win7-x86</RID>`
  - no files will be copied to the application's output folder, the correct dependencies are resolved during runtime using `deps.json`

**Publishing**
- `<TF>net471</TF>` &`<RID>any</RID>`
  - no files will be copied to the application's output folder, **the application does not work**
- `<TF>net471</TF>` & `<RID>win7-x86</RID>`
  - the files contained in folder `%rootFolder%/runtimes/{win7-x86}/native/` will be copied to the to the application's output folder (flat hierachy)
- `<TF>netcoreapp2.0</TF>` & `<RID>any</RID>`
  - the complete folder `%rootFolder%/runtimes/*` will be copied to the application's output folder, the correct dependencies are resolved during runtime using deps.json (no flat hierachy)
- `<TF>netcoreapp2.0</TF>` & `<RID>win7-x86</RID>`
  - the files contained in folder  `%rootFolder%/runtimes/{win7-x86}/native/` will be copied to the application's output folder, if they are available (flat hierachy). Otherwise the runtime tries to fallback to e.g. `runtimes/{win}/native/` or `runtimes/{any}/native/`.

You can see that netfx is not happy with non-matching runtime identifiers like "any" or "win" if there is only a `%rootFolder%/runtimes/{win7-x86}` folder available in the *.nupkg file. corefx, instead, gracefully falls back to the next less specific runtime identifier. See [this issue](https://github.com/NuGet/Home/issues/6645) for clarification (hopefully there will be an official answer to the inconsistent behavior soon).

In all cases, relative file path P/Invoke statements like `[DllImport(nativeFile.dll)]` work fine, no matter if it is a flat hierachy or if the whole `%rootFolder%/runtimes/*` folder is copied. 

Apart from the problem described above with exactly matching RID`s, I am not sure how find a suitable subfolder structure for HDF5_1.8 and HDF5_1.10. I think two different NuGet packages would be the cleanest solution. And I am not sure how this solution works with direct project references instead of NuGet packages references, but I think this is the way the Nuget team intended, although there are still open questions (at least for me).

**Comment by surban** [comment]
I have made the changes that Apollo3zehn suggested and everything seems to work fine, at least when testing using .NET Core 2.0 on Linux, Mac and Windows.

I have created a test project called `NugetTest` that consumes the built NuGet package and makes some simple HDF5 API calls to verify that the library and its native dependencies are working correctly. The test project is run on CI servers using Travis (Linux, MacOS) and Appveyor (Windows). However, I only tested consumption from .NET core, i.e. .NET framework and Mono might be failing to consume the package correctly.

Some unit tests are failing on MacOS, but this seems to be unrelated to packaging and the library is usable nonetheless. However, it would be nice to fix those issues in the future.

I removed support for HDF5 1.8 in my tree, since it was complicating the build and I think that you might as well update to HDF5 1.10 when you make the switch .NET core. I also removed the FAKE and Paket build scripts to streamline the build. They were only used to generate a legacy .nuspec file, which is now automatically generated from the .csproj file anyway. You can now build the repository by running `dotnet build`, run tests using `dotnet test` and create the NuGet package using `dotnet pack`.

Prebuilt packages are available from https://www.myget.org/feed/Packages/coreports

**Comment by Apollo3zehn** [comment]
Thanks for this quick update. I tested it also under .NET Core and Windows and everything works fine (using the feed https://www.myget.org/f/coreports/api/v2, hope that is the correct one). I made further tests under .NET Framework:

### new .csproj format + `<PackageReference>` + net471

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HDF.PInvoke" Version="1.10.4" />
  </ItemGroup>

</Project>
```

`<RuntimeIdentifier>any</RuntimeIdentifier>`: fails
`<RuntimeIdentifier>win7-x86</RuntimeIdentifier>`: fails
`<RuntimeIdentifier>win-x86</RuntimeIdentifier>`: works

### old .csproj format + `<PackageReference>` + net471

`<PlatformTarget>AnyCPU</PlatformTarget>`: fails
`<PlatformTarget>x86</PlatformTarget>`: works
`<PlatformTarget>x64</PlatformTarget>`: works

### old .csproj format + Packages.Config + net471

Installation of package fails due to dependency of System.Configuration. If the dependency is removed, installation is possible:

`<PlatformTarget>AnyCPU</PlatformTarget>`: fails
`<PlatformTarget>x86</PlatformTarget>`: fails
`<PlatformTarget>x64</PlatformTarget>`: fails

### Conclusion

- corefx works all the time
- netfx works only if you specify the correct RID and use `<PackageReference>`. I read about this today morning in several issues: AnyCPU and Packages.Config scenarios may require extra targets to copy the DLLs. See https://github.com/dotnet/sdk/issues/843 and https://github.com/ericsink/SQLitePCL.raw/issues/154#issuecomment-297474828

**Comment by Apollo3zehn** [comment]
Yes I think this would be the best solution until it is clear where the journey goes. I guess Microsoft will improve this once .NET Core 2.1 is released. 

I am not sure if HDF.PInvoke.Core would be the right name because it is in fact a .NET Standard package (at least right now). On the other hand, Hdf.PInvoke.NETStandard could be misleading in that it works everywhere.

**Comment by surban** [comment]
Hdf.PInvoke.NETStandard sounds fine to me.

Any comments from an official from HDFGroup? I don't want to publish packages on nuget.org without your approval.

**Comment by surban** [comment]
@Apollo3zehn I have made the changes that you requested. 

You can send me changes by forking my repo, i.e. surban/HDF.PInvoke, and then sending me pull requests. This way your changes will also be automatically tested on Linux, Mac and Windows using the CI servers I have set up.

**Comment by gheber** [comment]
Great work! Let me talk to our legal minds and get back to you.

**Comment by gheber** [comment]
@surban I want to give you an update on the choice of name. The timing is a little unfortunate as our products team is updating the branding guidelines as we speak. (The revision was triggered mainly by HDF, HDF5, etc., becoming registered trademarks of The HDF Group.)  Depending on how quickly you want to move on this, there are two options.

1. You wait until they've finalized their guidelines (It's not gonna take years, but might be a few weeks out.)
2. You go ahead with your current proposal, but will amend your project documentation with some kind of acknowledgement (of HDF.Pinvoke, HDF5, etc.) as set out in the forthcoming guidelines.

We and the whole HDF community appreciate your work and we want to make this as friction-less as possible, but we hope you understand our rationale.

**Comment by surban** [comment]
@gheber 
I will then go ahead and publish the package as `HDF.PInvoke.NetStandard` on NuGet. 
I will later update the documentation accordingly as requested by you once the guidelines are finished.

**Comment by silkfire** [comment]
@gheber What's the status on this PR? A year has gone but the official repo still doesn't support .NET Standard...

**Comment by Apollo3zehn** [comment]
The following is also an answer to @jjzieve question in surban's repo but I tried to answer/discuss it here.

In my opinion, the pull request is not fully compatible with this repo in its current form for several reasons:

- This repo has support for HDF 1.8 and 1.10, which is difficult (impossible?) to reflect in a single .NET Standard package.
- As mentioned [above](https://github.com/HDFGroup/HDF.PInvoke/pull/127?_pjax=%23js-repo-pjax-container#issuecomment-383857981), .NET framework has problems to resolve the matching native dependencies. So for backwards compatibility, it is required to keep post-build events or special .targets files to copy the native libs during build time. Maybe this has changed in the meantime.
- This PR relies on an automatic approach to download the native dependencies during build. I like this solution, but it conflicts with the current approach. Of course this can be solved.
- The READMEs of the pull request and this repo are incompatible (also a minor issue).

In general, I think the implementation of @surban is the way to go in future due to its simplicity and alignment with Microsofts way to publish multi-platform libs within a single package. 

Therefore, to keep compatibility, I would suggest we change this PR (or create a new one), so that in the end we get:

- A single official repo,
- which contains the original "HDF.PInvoke.csproj" and a new "HDF.PInvoke.NETStandard.csproj", which uses all the new features like:
  - new (simple) csproj format
  - `dotnet pack` to create the package, or create it during build using `<GeneratePackageOnBuild>`
  - references to platform specific native libraries in a hierachical structure like in this PR
- A native folder with the new native libraries included
- An appveyor file which builds for all three platforms (in this PR Travis is used for Linux and MacOS, but appveyor will support MacOS soon and then a single Powershell build script can be used for all platforms)
- two versions uploaded to Nuget: 
  - HDF.PInvoke
  - HDF.PInvoke.NETStandard (or **HDF.PInvoke.1.8.NETStandard** and **HDF.PInvoke.1.10.NETStandard**?)

Right now, without surban's nuget package, it would be very difficult to use HDF on .NET Core platforms. .NET Core has already become mature, and with its new runtime features like `Span<T>`, it is has significant advantages over .NET Framework (though also a few disadvantages :-)). Anyway, I think it is required to support both platforms, which is mainly a one-time effort.

@gheber and @surban, what do you think?

**Comment by gheber** [comment]
Let's get together in a Hangouts meet and talk this over! What's your timezone? Which days of the week work best for you?

**Comment by Apollo3zehn** [comment]
After discussing with @gheber, we created the new repository [HDFGroup/HDF.PInvoke.1.10](https://github.com/HDFGroup/HDF.PInvoke.1.10) which is based on the work of @surban (this PR) and which has been extended to reduce the overhead of having two very similar repositories as much as possible. The new repository refers to this one via the [Git submodule](https://git-scm.com/book/de/v1/Git-Tools-Submodule) feature. This way, all code changes in one repository will be reflected in the other repository (when something is changed, a simple `git submodule update` needs to be executed).

A first prerelease version has been published here: https://github.com/HDFGroup/HDF.PInvoke.1.10/releases and the package has been uploaded to NuGet: https://www.nuget.org/packages/HDF.PInvoke.1.10/. It is marked as pre-release since I could only test the package on my Windows machine and three different VMs (Ubuntu, CentOS, MacOS). When it becomes clear, that the package works for all users, I will remove the pre-release flag.

Unfortunately @surban is very busy right now, so we could not reuse his package named `HDF.PInvoke.NETStandard` and thus named it `HDF.PInvoke.1.10`. @surban, I hope this is fine for you.  Right now, I am the owner of the package but I already invited the HDF group to be the new owner.

**Comment by gheber** [comment]
I'm will look at this on Friday.

**Comment by bqstony** [comment]
what is the progress here?

**Comment by Apollo3zehn** [comment]
The current version of the .NET Standard compatible lib can be found here: https://www.nuget.org/packages/HDF.PInvoke.1.10/.

**Comment by silkfire** [comment]
Could we not close this PR as this already seems resolved?

**Pull request closed without merging**
