### PR TITLE
Fix for issue #68.

### PR DESCRIPTION
**Pull request by gheber**
We can't have a fixed array of pointers. For the expected storage
layout, we have to go with a Mickey Mouse solution.

### CODE REVIEW

**Comment by hokb** [comment]
Could we add a test to check if actually something useful is put into any 'retries'? or we might initialize some members with non-zero IntPtr and see if the function sets it to Zero.
It seems your approach is the best we can do - when sticking to the *no-code* policy.

**Comment by gheber** [comment]
The library is going to initialize the retry arrays as described in the [Reference Manual](https://www.hdfgroup.org/HDF5/doc/RM/RM_H5F.html#File-GetMetadataReadRetryInfo). This will occur only if a checksum mismatch occurs during a read operation, and a retry is triggered. The test setup would require a true SWMR writer/reader setup w/ different processes, and may not happen on a local file system in a predictable manner, if at all.

**Comment by gheber** [comment]
Let's initialize the retries with some bogus values and see if the library initializes/changes them.

**Comment by gheber** [comment]
I have changed the `H5Fget_metadata_read_retry_infoTestSWMR1` to test that the library initializes the fields of `retry_info_t` with `NULL`. I think it's ready. (I also snuck in the keyfile for a strong assembly name.)

**Pull request merged**
