### PR TITLE
Misplaced [Out] keywords and test fixes.

### PR DESCRIPTION
**Pull request by gheber**
There were several misplaced [Out] keywords, which caused errors in clients such as Mathematica.

The `H5[g,s]et_chunk_opts` test failed, because the implementation has those functions fail in the absence of chunking. Fixed by adding bogus chunking.

### CODE REVIEW

**Comment by DSanchen** [comment]
I assume, you already checked with the native library, that all places where the [out] attribute was misplaced, the library actually expects pre-allocated (by the caller) arrays....

**Comment by gheber** [comment]
All the native library has are comments like this: `/* Out */` :smile: It's interesting that it seemed to make no difference in the tests.

**Comment by hokb** [comment]
Hm, not sure about the 'misplaced'. What makes you assume that we don't need them? 
Most places where the [Out] attribute has been removed in this commit seem to refer to blittable arrays. The default behavior for the interop marshaller in this case is to implicitly marshal the parameter as if the [In] attribute was applied only.  
However, since we have a [blittable array](https://msdn.microsoft.com/en-us/library/23acw07k(v=vs.110).aspx) what actually happens is that a pointer to the array is passed directly to the unmanged part. The array gets pinned during the call appropriately and automatically.   
So this behavior really corresponds to [In][Out]. This is why the function is working without the [Out] attribute applied. 
And this corresponds to what we really want most the time: we want the predefined data to pass [In] to the C API and in some places we want to allow the unmanaged side to change our managed buffer and to retrieve those changes back [Out] of the unmanaged part. 
Pinning is applied instead of copying _when possible_. While pinning is possible when working on shared memory in the same process there are situations where those marshalling attributes would actually make a difference. Remoting and cross apartment calls in COM being 2 examples. Here the array would not be pinned but copied forth and back. With the [In] attribute only it will only be copied once when entering. With the [Out] attribute only it will also be copied only once when returning. Potentially, the bugs you mentioned refer back to one of these cases? Maybe we were just missing [In]?   
So my suggestion is to make a conscious decision about the intended behavior and to apply [In] and [Out] where needed instead of leaving it up the marshaller to decide some (often poorly documented) default behavior. 
Regarding the memory owner: if there are places in the lib where we ought to _receive_ an array from the HDF5 libs (unmanaged memory) we need to handle this differently anyway by using ref IntPtr.

**Comment by hokb** [comment]
[MarshalAs(UnmanagedType.LPArray)] - not sure why we need this one?

**Comment by hokb** [comment]
[Out] on StringBuilder is not needed. StringBuilder is an exception to the "[In] by default" rule. It is always [marshalled by providing a pointer](https://msdn.microsoft.com/en-us/library/23acw07k(v=vs.110).aspx) to its inner buffer which corresponds to [In][Out] behavior. But I vote on being explicit here also, because of the reasons explained above.

**Comment by gheber** [comment]
@hokb thanks for the comments. I'll create an [In]{Out] version w/ one of the calls where the user had trouble and see what happens.

**Comment by gheber** [comment]
> Regarding the memory owner: if there are places in the lib where we ought to receive an array from the HDF5 libs (unmanaged memory) we need to handle this differently anyway by using `ref IntPtr`.

Yes, I think we got those (few places) covered.

**Pull request merged**
