### PR TITLE
Move to .Net 2.0

### PR DESCRIPTION
**Pull request by JanWosnitza**
#101

> Would be beneficial to support .Net 2.0. There are only a few .Net 4.5 convenience features in use.
> Also problems like the one in #100 wouldn't occur.
> 
> I made the required modifications for .Net 2.0 on this branch

### CODE REVIEW

**Comment by gheber** [comment]
This looks good to me. @hokb , do you see any issues?

**Comment by JanWosnitza** [comment]
I think this is also partially related to #57 (similar problem category as #100)

**Comment by hokb** [comment]
Have we checked that it is actually possible to *build* using version 2.0 SDK tools? (Or don't we want this?)

**Comment by JanWosnitza** [comment]
Nope, haven't checked that. Supporting an old run-time seems fine, since has minor drawbacks only, but do we have to support a ten year old tool-chain? Not even sure if it still works properly ;)

**Comment by gheber** [comment]
Sorry for the goof-up. I should have pulled them in the opposite order. Would you mind rebasing w/ master and merging this pull request. I'll pull it after that. Thanks, G.

**Comment by JanWosnitza** [comment]
No problem, now it's rebased :)

#### Off topic:
Btw. I noticed that my claim about the automatic version selection is wrong. It doesn't take the upper most entry in `RELEASE_NOTES.md` but the one with the highest version-number. Thus it takes the highest 1.10 entry always when you don't specify `ver=1.8`.

To clarify this I added printing the used version after the build (even though this isn't the appropriate branch :P it's a one-liner)

**Comment by gheber** [comment]
Thanks a lot.

**Pull request merged**
