### PR TITLE
Automatic NuGet package generation

### PR DESCRIPTION
**Pull request by JanWosnitza**
This PR contains #105 and #74.

### Usage
To build the project simply run `build.cmd`. This will build the latest version (upper most entry in `RELEASE_NOTES.md`).
It's possible to specify a specific version (1.8 or 1.10): `build.cmd ver=1.8` or `build.cmd ver=1.10`.

`build.cmd CMD ver=VER`:

CMD | Description
------|--------------
`Build` | Builds the solution (using MSBuild)
`Test` | Executes the UnitTests (using MSTest). This is the default command.
`GenTemplate` | Generates the template file required by Paket to generate the NuGet-package (`paket.template`)
`NuGet` | Pack the NuGet-package (`temp/HDF.PInvoke.VERSION.nupkg`)
`Deploy` | Push the NuGet-package to the NuGet server

**Deploy is not untested.**

### "Explanation"

All of this is specified within `build.fsx`.
An .fsx file is an F#-Script file. It will be executed by Fake.exe when calling build.cmd. Since Fake isn't part of the repository Paket will download it. This is pretty much the recommended way.

### Examples
```
build.cmd Test ver=1.10
build.cmd NuGet ver=1.8
```

### UPDATE
Renamed `RunTests` to `Test` so it is shorter and is more similar to the other commands.

### CODE REVIEW

**Comment by gheber** [comment]
Thanks for all the hard work! I'll check this out tomorrow. (It's MLK Day here)

**Comment by JanWosnitza** [comment]
I tried to keep the changeset small.

But I think it would be good to split 1.8 and 1.10 into 2 projects like this:

* HDF.PInvoke (Solution)
  * 1.8
    * HDF.PInvoke 1.8 (Project)
    * HDF.PInvoke 1.8 UnitTests (Project)
  * 1.10
    * HDF.PInvoke 1.10 (Project)
    * HDF.PInvoke 1.10 UnitTests (Project)

So the 2 library versions can be built and tested simultaneously.

**Comment by gheber** [comment]
1. Never put `#` in a path name.
2. `"Platform", "Any CPU"` missing in `build.fsx`
3. Missing `TestResults` directory

**Comment by JanWosnitza** [comment]
1. created #107
2. added
3. fixed

**Comment by gheber** [comment]
Outstanding work! I'm sorry that it took so long. I just built the 1.8.18 native binaries and will use this new mechanism to roll the 1.8.18 NuG(g)ets.

**Pull request merged**
