### PR TITLE
Include the native C/C++ in the NuGet packages.

### PR DESCRIPTION
**Pull request by gheber**
I forgot to include the native DLLs in the NuGet packages. I re-rolled them and updated the assembly file versions in line with our numbering scheme.

### CODE REVIEW

**Comment by hokb** [comment]
I don't have a reference ready but the C runtime libs should be installed by the install packages provided by Microsoft for the corresponding Visual Studio version / platform target. However, it can be convenient to have a matching DLL delivered in the nuget package. On the other hand it raises some certain risks to the user. One is to mix up different C runtime versions in the same assembly and to produce conflicts.

We should put a hint into the docu, at least.

**Comment by hokb** [comment]
Edit: ... different runtime versions in the same _process_ ...

**Comment by gheber** [comment]
I see your point. `MSVCR120.dll` is a dependency of `hdf5.dll` (per `dumpbin /dependents`). Maybe we can offer two lines of NuGet packages? We would have one line that includes the C-runtime and another that doesn't.

**Comment by gheber** [comment]
Versioning would be the same, of course.

**Comment by hokb** [comment]
I am open to this but I would prefer to go with the [recommendation](https://msdn.microsoft.com/en-us/library/ms235299.aspx) regarding deployment of VC++ runtime modules. Some reasoning: 

Providing two options produces the overhead of another decision on the user side. At this point some users will not be aware of the implications. Most users will have a recent enough version of VS installed anyway - so not hit any issue on their machine without the vcrt included in the package (because it will be found on the System32). But they need to now about the dependency when packaging their installer for deployment to an end user. 

I'd suggest not to include the vcrt dlls in the nuget package but to make it clear in the documentation that these dependencies exist and should be deployed with the custom application (via merge modules from MS though).

**Comment by gheber** [comment]
I see your point and will update the documentation / re-roll the NuGet.

**Pull request closed without merging**
